//------------
//System Values
//------------
var STAGE_WIDTH = 600,
	STAGE_HEIGHT = 400,
	TIME_PER_FRAME = 33, //this equates to 30 fps
	GAME_FONTS = "bold 20px sans-serif";

var PATH_CHAR = "labb.png";

var CHAR_WIDTH = 64,
	CHAR_HEIGHT = 64,
	CHAR_START_X = 200,
	CHAR_START_Y = 200,
	CHAR_SPEED = 5,
	IMAGE_START_X = 0,
	IMAGE_START_NORTH_Y = 0,
	IMAGE_START_EAST_Y = 64,
	IMAGE_START_SOUTH_Y = 128,
	IMAGE_START_WEST_Y = 192,	
	IMAGE_ATTACK_Y = 256,
	IMAGE_RUN_Y = 320,
	IMAGE_JUMP_Y = 384,
	IMAGE_DIE_Y = 448,
	SPRITE_WIDTH = 256;

var TEXT_PRELOADING = "Loading ...", 
	TEXT_PRELOADING_X = 200, 
	TEXT_PRELOADING_Y = 200;
	
	
	
	